In [1]:
from PIL import Image
import os, sys
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
path = "/Users/Stacy Steed/Data/rgb/cam-connector/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [3]:
read = lambda imname: np.asarray(Image.open(imname).convert("RGB"))

cc = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
cc_array = np.array(cc, dtype='uint8')

In [4]:
cc_array

array([[[[255, 255, 255],
         [255, 255, 255],
         [253, 253, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[252, 252, 252],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 254, 254],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [252, 252, 252],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [253, 253, 253],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [5]:
len(cc_array)

946

In [6]:
cc_labels = np.linspace(0, 0, 946, dtype='uint8')

In [7]:
path = "/Users/Stacy Steed/Data/rgb/anchor-screw/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [8]:
anch = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
anch_array = np.array(anch, dtype='uint8')

In [9]:
anch_array

array([[[[255, 255, 253],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 253],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [10]:
len(anch_array)

1019

In [11]:
anch_labels = np.linspace(1, 1, 1019, dtype='uint8')

In [12]:
path = "/Users/Stacy Steed/Data/rgb/eye-bolt/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [13]:
eb = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
eb_array = np.array(eb, dtype='uint8')

In [14]:
eb_array

array([[[[255, 253, 255],
         [255, 254, 255],
         [255, 254, 255],
         ...,
         [255, 255, 253],
         [255, 255, 253],
         [255, 255, 253]],

        [[255, 254, 255],
         [254, 252, 255],
         [251, 251, 253],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[254, 255, 255],
         [254, 255, 255],
         [254, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 255, 255],
         [254, 255, 255],
         [254, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [15]:
len(eb_array)

1000

In [16]:
eb_labels = np.linspace(2, 2, 1000, dtype='uint8')

In [17]:
path = "/Users/Stacy Steed/Data/rgb/extruded-u-nut/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [18]:
un = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
un_array = np.array(un, dtype='uint8')

In [19]:
un_array

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        

In [20]:
len(un_array)

1057

In [21]:
un_labels = np.linspace(3, 3, 1057, dtype='uint8')

In [22]:
path = "/Users/Stacy Steed/Data/rgb/jack-nut/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [23]:
jn = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
jn_array = np.array(jn, dtype='uint8')

In [24]:
jn_array

array([[[[211, 205, 193],
         [211, 205, 193],
         [209, 203, 191],
         ...,
         [217, 208, 203],
         [217, 210, 204],
         [217, 210, 204]],

        [[211, 205, 193],
         [210, 204, 192],
         [210, 202, 191],
         ...,
         [217, 208, 203],
         [217, 210, 204],
         [217, 210, 204]],

        [[211, 203, 192],
         [210, 202, 191],
         [208, 200, 189],
         ...,
         [217, 208, 203],
         [217, 210, 204],
         [217, 210, 204]],

        ...,

        [[197, 190, 182],
         [198, 191, 183],
         [199, 192, 184],
         ...,
         [213, 206, 200],
         [214, 207, 201],
         [212, 207, 201]],

        [[196, 189, 181],
         [197, 190, 182],
         [198, 191, 183],
         ...,
         [213, 206, 200],
         [214, 207, 201],
         [212, 207, 201]],

        [[196, 189, 181],
         [197, 190, 182],
         [198, 191, 183],
         ...,
         [213, 206, 200],
        

In [25]:
len(jn_array)

1168

In [26]:
jn_labels = np.linspace(4, 4, 1168, dtype='uint8')

In [27]:
x = np.concatenate((cc_array, anch_array, eb_array, un_array, jn_array), axis=0)

In [28]:
y = np.concatenate((cc_labels, anch_labels, eb_labels, un_labels, jn_labels), axis=0)

In [29]:
# Use train_test_split to create the necessary training and test groups
X_train, x2, y_train, y2 = train_test_split(x, y, test_size=0.36)
X_val, X_test, y_val, y_test = train_test_split(x2, y2, test_size=0.5)

In [30]:
print(len(X_train))
print(len(X_test))
print(len(X_val))
print(len(y_train))
print(len(y_test))
print(len(y_val))

3321
935
934
3321
935
934


In [31]:
np.save('X-train-rgb.npy', X_train)
np.save('y-train-rgb.npy', y_train)
np.save('X-test-rgb.npy', X_test)
np.save('y-test-rgb.npy', y_test)
np.save('X-val-rgb.npy', X_val)
np.save('y-val-rgb.npy', y_val)