In [1]:
from PIL import Image
import os, sys
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
path = "/Users/Stacy Steed/Data/images/cam-connector/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [3]:
read = lambda imname: np.asarray(Image.open(imname).convert("L"))

cc = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
cc_array = np.array(cc, dtype='uint8')

In [4]:
cc_array

array([[[255, 255, 253, ..., 255, 255, 255],
        [252, 255, 255, ..., 255, 255, 255],
        [254, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 252, 255, ..., 255, 255, 255],
        [255, 253, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 252, ..., 255, 255, 255],
        [249, 254, 255, ..., 255, 255, 255],
        [252, 255, 255, ..., 255, 255, 255],
        ...,
        [253, 250, 255, ..., 255, 255, 255],
        [255, 252, 255, ..., 255, 255, 255],
        [255, 255, 253, ..., 255, 255, 255]],

       [[252, 254, 255, ..., 255, 254, 254],
        [251, 254, 255, ..., 255, 254, 254],
        [255, 254, 253, ..., 255, 255, 254],
        ...,
        [254, 254, 254, ..., 255, 255, 254],
        [254, 254, 254, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       ...,

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0

In [5]:
len(cc_array)

946

In [6]:
cc_labels = np.linspace(0, 0, 946, dtype='uint8')

In [7]:
path = "/Users/Stacy Steed/Data/images/anchor-screw/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [8]:
anch = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
anch_array = np.array(anch, dtype='uint8')

In [9]:
anch_array

array([[[254, 255, 255, ..., 255, 255, 255],
        [254, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[254, 254, 255, ..., 254, 255, 255],
        [254, 254, 255, ..., 254, 255, 255],
        [254, 254, 255, ..., 254, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[254, 254, 254, ..., 254, 255, 255],
        [254, 254, 254, ..., 254, 255, 255],
        [254, 254, 254, ..., 254, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [254, 255, 254, ..., 255, 255, 255],
        [254, 255, 254, ..., 255, 255, 255]],

       ...,

       [[161, 159, 158, ..., 141, 137, 134],
        [160, 159, 157, ..., 137, 133, 130],
        [159, 157, 156, ..., 132, 129, 127

In [10]:
len(anch_array)

1019

In [11]:
anch_labels = np.linspace(1, 1, 1019, dtype='uint8')

In [12]:
path = "/Users/Stacy Steed/Data/images/eye-bolt/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [13]:
eb = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
eb_array = np.array(eb, dtype='uint8')

In [14]:
eb_array

array([[[253, 254, 254, ..., 254, 254, 254],
        [254, 252, 251, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [254, 254, 254, ..., 255, 255, 255],
        [254, 254, 254, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[250, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 255, 255, 255],
        [253, 252, 253, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[253, 254, 254, ..., 254, 254, 254],
        [254, 252, 251, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [254, 254, 254, ..., 255, 255, 255],
        [254, 254, 254, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       ...,

       [[254, 254, 254, ..., 254, 254, 254],
        [253, 254, 254, ..., 254, 254, 254],
        [253, 254, 254, ..., 255, 255, 255

In [15]:
len(eb_array)

1000

In [16]:
eb_labels = np.linspace(2, 2, 1000, dtype='uint8')

In [17]:
path = "/Users/Stacy Steed/Data/images/extruded-u-nut/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [18]:
un = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
un_array = np.array(un, dtype='uint8')

In [19]:
un_array

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[254, 254, 254, ..., 253, 253, 253],
        [254, 254, 254, ..., 253, 253, 253],
        [254, 254, 254, ..., 255, 254, 254],
        ...,
        [254, 254, 254, ..., 253, 254, 254],
        [254, 254, 254, ..., 254, 254, 254],
        [254, 254, 254, ..., 255, 255, 255]],

       [[248, 249, 255, ..., 255, 252, 243],
        [255, 249, 252, ..., 253, 255, 255],
        [247, 251, 255, ..., 244, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       ...,

       [[ 99, 104, 102, ..., 150, 151, 153],
        [ 99, 100,  98, ..., 153, 156, 161],
        [ 94,  98,  98, ..., 156, 162, 168

In [20]:
len(un_array)

1057

In [21]:
un_labels = np.linspace(3, 3, 1057, dtype='uint8')

In [22]:
path = "/Users/Stacy Steed/Data/images/jack-nut/"
dirs = os.listdir(path)

def resize():
    for item in dirs:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(path+item)
            imResize = im.resize((28,28), Image.ANTIALIAS)
            imResize.save(f + '.jpg', 'JPEG', quality=90)

resize()

In [23]:
jn = [read(os.path.join(path, filename)) for filename in os.listdir(path)]
jn_array = np.array(jn, dtype='uint8')

In [24]:
jn_array

array([[[205, 205, 203, ..., 210, 211, 211],
        [205, 204, 203, ..., 210, 211, 211],
        [204, 203, 201, ..., 210, 211, 211],
        ...,
        [191, 192, 193, ..., 207, 208, 207],
        [190, 191, 192, ..., 207, 208, 207],
        [190, 191, 192, ..., 207, 208, 207]],

       [[207, 206, 206, ..., 212, 213, 213],
        [207, 207, 206, ..., 212, 213, 213],
        [206, 206, 206, ..., 212, 213, 213],
        ...,
        [194, 194, 195, ..., 210, 210, 211],
        [193, 193, 194, ..., 210, 210, 211],
        [192, 193, 194, ..., 210, 210, 211]],

       [[206, 206, 205, ..., 214, 214, 215],
        [206, 206, 205, ..., 214, 215, 215],
        [205, 205, 205, ..., 214, 215, 215],
        ...,
        [197, 197, 197, ..., 212, 212, 213],
        [195, 195, 195, ..., 212, 212, 213],
        [194, 194, 195, ..., 212, 212, 213]],

       ...,

       [[201, 202, 202, ..., 204, 207, 209],
        [199, 199, 198, ..., 202, 205, 207],
        [196, 195, 193, ..., 201, 204, 206

In [25]:
len(jn_array)

1168

In [26]:
jn_labels = np.linspace(4, 4, 1168, dtype='uint8')

In [27]:
x = np.concatenate((cc_array, anch_array, eb_array, un_array, jn_array), axis=0)

In [28]:
y = np.concatenate((cc_labels, anch_labels, eb_labels, un_labels, jn_labels), axis=0)

In [29]:
# Use train_test_split to create the necessary training and test groups
X_train, x2, y_train, y2 = train_test_split(x, y, test_size=0.36)
X_val, X_test, y_val, y_test = train_test_split(x2, y2, test_size=0.5)

In [30]:
print(len(X_train))
print(len(X_test))
print(len(X_val))
print(len(y_train))
print(len(y_test))
print(len(y_val))

3321
935
934
3321
935
934


In [31]:
np.save('X-train.npy', X_train)
np.save('y-train.npy', y_train)
np.save('X-test.npy', X_test)
np.save('y-test.npy', y_test)
np.save('X-val.npy', X_val)
np.save('y-val.npy', y_val)